---
- name: Get hostname of remote machine
  hosts: remote_host
  gather_facts: false
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Show hostname
      debug:
        var: hostname_output.stdout
